# Training Config
device: "cuda:7"
env: walker
n_envs: 1
max_training_steps: 3000000
max_episode_len: 1000
buffer_len: 10000
batch_size: 4096
lr_actor: 0.0003
lr_critic: 0.001
gamma: 0.99
len_history: 5
random_action: false

# Domain randomization [domain_name, lower_bound, upper_bound, step_size] (lower, upper bounds are multipliers)
# domain_randomization:
#   - [m, 0.5, 1.51, 0.25]
#   - [l, 0.5, 1.51, 0.25]

# Model (PPO) Config
model_type: PPO
hidden_dim: &hidden_dim 64
eps_clip: 0.20
K_epochs: 15

has_continuous_action_space: true
action_std: 0.6
action_std_decay_rate: 0.05
min_action_std: 0.1
action_std_decay_freq: 250000

# Test
eval_freq: 100000
test_epsilon: 0.0
test_max_episode_len: 1000
test_num_episodes: 10
test_gui: true

# Logging / Saving
log_freq: 1000
checkpoint_num: 10

# --- Network Candidates ----
act: &act Tanh
actor_net: &actor_net
  - [Linear, auto, *hidden_dim, {}]
  - *act
  - [Linear, *hidden_dim, *hidden_dim, {}]
  - *act
  - [Linear, *hidden_dim, auto, {}]
critic_net: &critic_net
  - [Linear, auto, *hidden_dim, {}]
  - *act
  - [Linear, *hidden_dim, *hidden_dim, {}]
  - *act
  - [Linear, *hidden_dim, auto, {}]

# --- Models ---
actor: *actor_net
critic: *critic_net